Telegram bot
HSE-Courseworks/EmemeBot pull request #44
Opened 2023-05-03 11:42 UTC by maksmolchdmitr

2023-05-06 15:44 UTC, kryakobess requested changes

2023-05-06 15:44 UTC, kryakobess commented on EmemeSenderFunctionality/pom.xml
> +            <version>6.0.6</version>
Зачем оно если уже есть стартер?

2023-05-06 15:44 UTC, kryakobess commented on EmemeSenderFunctionality/src/main/java/ru/mamakapa/ememeSenderFunctionality/bot/service/EmemeEmailHttpClient.java
> +@HttpExchange("http://localhost:8080/")
Не хардкодь путь к сервису, добавь в проперти лучше

2023-05-06 15:44 UTC, kryakobess commented on EmemeSenderFunctionality/src/main/java/ru/mamakapa/ememeSenderFunctionality/bot/service/EmemeEmailHttpClient.java
> +    EmailData addEmail(
Exchange

2023-05-06 16:00 UTC, maksmolchdmitr commented on EmemeSenderFunctionality/pom.xml
> +            <version>6.0.6</version>
Для этого

2023-05-06 16:00 UTC, maksmolchdmitr commented on EmemeSenderFunctionality/pom.xml
> +            <version>6.0.6</version>
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.support.WebClientAdapter;
import org.springframework.web.service.invoker.HttpServiceProxyFactory;

2023-05-06 16:00 UTC, maksmolchdmitr commented on EmemeSenderFunctionality/pom.xml
> +            <version>6.0.6</version>
`@Bean
    EmemeEmailHttpClient ememeEmailHttpClient() {
        HttpServiceProxyFactory httpServiceProxyFactory = HttpServiceProxyFactory.builder()
                .clientAdapter(WebClientAdapter.forClient(
                        WebClient.builder()
                                .clientConnector(new ReactorClientHttpConnector(HttpClient
                                        .create()
                                        .responseTimeout(Duration.ofSeconds(TIMEOUT_RESPONSE))
                                ))
                                .build()
                ))
                .build();
        return httpServiceProxyFactory.createClient(EmemeEmailHttpClient.class);
    }`

2023-05-06 16:01 UTC, maksmolchdmitr commented on EmemeSenderFunctionality/pom.xml
> +            <version>6.0.6</version>
`
@Bean
    EmemeEmailHttpClient ememeEmailHttpClient() {
        HttpServiceProxyFactory httpServiceProxyFactory = HttpServiceProxyFactory.builder()
                .clientAdapter(WebClientAdapter.forClient(
                        WebClient.builder()
                                .clientConnector(new ReactorClientHttpConnector(HttpClient
                                        .create()
                                        .responseTimeout(Duration.ofSeconds(TIMEOUT_RESPONSE))
                                ))
                                .build()
                ))
                .build();
        return httpServiceProxyFactory.createClient(EmemeEmailHttpClient.class);
    }
`

2023-05-06 16:01 UTC, maksmolchdmitr commented on EmemeSenderFunctionality/src/main/java/ru/mamakapa/ememeSenderFunctionality/bot/service/EmemeEmailHttpClient.java
> +@HttpExchange("http://localhost:8080/")
Уже сделал

2023-05-06 16:01 UTC, maksmolchdmitr commented on EmemeSenderFunctionality/src/main/java/ru/mamakapa/ememeSenderFunctionality/bot/service/EmemeEmailHttpClient.java
> +    EmailData addEmail(
Да - сделал

2023-05-08 08:47 UTC, kryakobess approved these changes

2023-05-08 09:34 UTC, merged